# SITE CONFIGURATION
title: Society of Physics Students at UVA # your site title
author: Society of Physics Students at UVA # You :P
description: > # Meta description of Homepage
  We are a social community of physics majors at the University of Virginia. We
  have three focuses: social inclusion within our chapter, providing access to 
  research and academic resources, and representing the voice of undergraduates
  in the UVA physics department.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spsatuva.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Society of Physics Students at UVA
  links:
    - https://www.facebook.com/SPSatUVA
    - https://github.com/spsatuva

# THEME SETTINGS

tagline: >
  A group of physics majors focused on community, public outreach, and academic excellence.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

# Either img or text to select logo type - see _includes/header.html
logo-type: 'text'
# Image to use - must be in _includes/
logo-img: logo.svg
# Text to use
logo-text: 'SPS at UVA'

email: spsatuva@gmail.com # email for form submission

# twitter_username: spsatuva # replace with your_twitter_username or comment to remove link from footer
github_username:  spsatuva # replace with your_github_username or comment to remove link from footer
instagram_username: spsatuva # replace with your_instagram_username or comment to remove link from footer
facebook_username: SPSatUVA # replace with your_facebook_username or comment to remove link from footer

disqus:
  shortname: spsatuva-github-io # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: false

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
# remote_theme: janczizikow/sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages', 'docs']
permalink: /:year/:month/:day/:title/

collections:
  docs:
    output: true    

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
